{
 "title": "Techscrum Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "ECS CPU and Memory Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "aws_ecs_cpuutilization_average", "legendFormat": "__auto" },
    {
     "expr": "aws_ecs_memory_utilization_average",
     "legendFormat": "__auto"
    },
    { "expr": "aws_ecs_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Route53 HealthCheck Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "aws_route53_health_check_percentage_healthy_average",
     "legendFormat": "__auto"
    },
    {
     "expr": "aws_route53_health_check_percentage_healthy_maximum",
     "legendFormat": "__auto"
    },
    {
     "expr": "aws_route53_health_check_percentage_healthy_minimum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ApplicationELB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "aws_applicationelb_active_connection_count_sum",
     "legendFormat": "__auto"
    },
    {
     "expr": "aws_applicationelb_httpcode_elb_4_xx_count_sum",
     "legendFormat": "__auto"
    },
    {
     "expr": "aws_applicationelb_new_connection_count_sum",
     "legendFormat": "__auto"
    },
    {
     "expr": "aws_applicationelb_httpcode_target_4_xx_count_sum",
     "legendFormat": "__auto"
    },
    {
     "expr": "aws_applicationelb_target_response_time_average",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "S3 Bucket Size Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "aws_s3_bucket_size_bytes_average",
     "legendFormat": "__auto"
    },
    {
     "expr": "aws_s3_bucket_size_bytes_maximum",
     "legendFormat": "__auto"
    },
    {
     "expr": "aws_s3_bucket_size_bytes_minimum",
     "legendFormat": "__auto"
    },
    { "expr": "aws_s3_bucket_size_bytes_sum", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Route53 HelathCheck Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "aws_route53_health_check_status_average",
     "legendFormat": "__auto"
    },
    {
     "expr": "aws_route53_health_check_status_maximum",
     "legendFormat": "__auto"
    },
    {
     "expr": "aws_route53_health_check_status_minimum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cloudfront 4xx/5xx Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "aws_cloudfront_4xx_error_rate_sum",
     "legendFormat": "__auto"
    },
    {
     "expr": "aws_cloudfront_5xx_error_rate_sum",
     "legendFormat": "__auto"
    },
    { "expr": "aws_cloudfront_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "S3 Number of Objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "aws_s3_number_of_objects_average",
     "legendFormat": "__auto"
    },
    {
     "expr": "aws_s3_number_of_objects_maximum",
     "legendFormat": "__auto"
    },
    {
     "expr": "aws_s3_number_of_objects_minimum",
     "legendFormat": "__auto"
    },
    { "expr": "aws_s3_number_of_objects_sum", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cloudfront Download/Upload Sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "aws_cloudfront_bytes_downloaded_sum",
     "legendFormat": "__auto"
    },
    {
     "expr": "aws_cloudfront_bytes_uploaded_sum",
     "legendFormat": "__auto"
    },
    { "expr": "aws_cloudfront_info", "legendFormat": "__auto" }
   ]
  }
 ]
}