apiVersion: v1alpha1
discovery:
  jobs:
    - type: AWS/S3
      regions: [ap-southeast-2]
      period: 86400
      length: 86400
      metrics:
        - name: NumberOfObjects
          statistics: [Average]
        - name: BucketSizeBytes
          statistics: [Average]

    - type: AWS/Route53
      regions: [us-east-1]
      metrics: 
        - name: HealthCheckStatus
          statistics: [Average, Minimum, Maximum, Sum]
          length: 60000
          period: 60000
        - name: HealthCheckPercentageHealthy
          statistics: [Average, Minimum, Maximum, Sum]
          length: 60000
          period: 60000
      
    - type: AWS/CloudFront
      regions: [us-east-1]
      dimensionNameRequirements: [DistributionId, Region]
      metrics: 
        - name: Requests
          length: 60000
          period: 60000
          statistics: [Sum]
        - name: TotalErrorRate
          length: 60000
          period: 60000
          statistics: [Sum]
        - name: BytesDownloaded
        # Refers to the total number of bytes downloaded from your CloudFront distribution.
          length: 60000
          period: 60000
          statistics: [Sum]
        - name: 4xxErrorRate
          length: 60000
          period: 60000
          statistics: [Sum]
        - name: 5xxErrorRate
          length: 60000
          period: 60000
          statistics: [Sum]    

    - type: AWS/ECS
      regions: [ap-southeast-2]
      period: 60000
      length: 60000
      metrics:
        - name: CPUReservation
          statistics:
            - Average
        - name: MemoryReservation
          statistics:
            - Average
        - name: CPUUtilization
          statistics:
            - Average
        - name: MemoryUtilization
          statistics:
            - Average
    
    - type: AWS/EC2
      regions: [us-east-1]
      metrics:
        - name: CPUUtilization
          statistics:
            - Average
     
    - type: AWS/ApplicationELB
      regions: [ap-southeast-2]
      period: 300
      length: 300
      metrics:
        - name: HealthyHostCount
          # The number of healthy instances in your load balancer.
          statistics: [Sum]

        - name: UnHealthyHostCount
          # The number of unhealthy instances in your load balancer.
          statistics: [Sum]

        - name: RequestCount
          # The number of requests processed by your load balancer.
          statistics: [Average]

        - name: TargetResponseTime
          # The time taken to send a response to the client after the request has been processed. 
          statistics: [Average, Minimum, Maximum]

        - name: ActiveConnectionCount
          # The number of active TCP connections.
          statistics: [Sum]

        - name: NewConnectionCount
          # This metric tracks the total number of new TCP connections established from clients to the load balancer and from the load balancer to targets.
          statistics: [Sum]

        - name: RejectedConnectionCount
          # The total number of connections that were rejected because the load balancer had reached its maximum number of connections.
          statistics: [Sum]

        - name: TargetConnectionErrorCount
          # The total count of connection errors with targets.
          statistics: [Sum]

        - name: IPv6RequestCount
          # The number of requests made to the load balancer using IPv6.
          statistics: [Sum]

        - name: RequestCountPerTarget
          # The average number of requests received by each target in a target group.
          statistics: [Sum]

        - name: NonStickyRequestCount
          # The total number of non-sticky session requests.
          statistics: [Sum]

        - name: HTTPCode_Target_2XX_Count
          # will count the number of '2XX' HTTP response codes returned by the targets.
          statistics: [Sum]

        - name: HTTPCode_Target_3XX_Count
          # will count the number of '3XX' HTTP response codes returned by the targets.
          statistics: [Sum]

        - name: HTTPCode_Target_4XX_Count
          # will count the number of '4XX' HTTP response codes returned by the targets.
          statistics: [Sum]

        - name: HTTPCode_Target_5XX_Count
          # will count the number of '5XX' HTTP response codes returned by the targets.
          statistics: [Sum]

        - name: HTTPCode_ELB_3XX_Count
          # These metrics count the HTTP response codes generated by the load balancer. 
          statistics: [Sum]
        - name: HTTPCode_ELB_4XX_Count
          statistics: [Sum]
        - name: HTTPCode_ELB_5XX_Count
          statistics: [Sum]

        - name: ProcessedBytes
          # The total number of bytes processed by the load balancer.
          statistics: [Sum]

        - name: IPv6ProcessedBytes
          # The total number of bytes processed by the load balancer for requests made over IPv6.
          statistics: [Sum]

        - name: ConsumedLCUs
          # An LCU (Load Balancer Capacity Unit) measures the dimensions on which the Application Load Balancer processes your traffic. This metric counts the number of LCUs consumed by your load balancer.
          statistics: [Average]

        - name: ClientTLSNegotiationErrorCount
         # The number of TLS connections initiated by the client that did not establish a session with the load balancer due to a TLS error generated by the client.
          statistics: [Sum]

        - name: TargetTLSNegotiationErrorCount
          # The number of TLS connections initiated by the load balancer that did not establish a session with the target due to a TLS error generated by the target.
          statistics: [Sum]

        - name: RuleEvaluations
          # The number of rules processed by the listener.
          statistics: [Sum]
        



